import turtle
screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor("hotpink")
t=turtle.Turtle()



# intro screen
t.penup()
t.goto(0,150)
t.pendown()
t.setheading(0)
t.pencolor("grey")
t.fillcolor("grey")
t.begin_fill()
t.write("My Presentation", font=("Arial", 30, "bold"), align="center")
t.penup()
t.goto(0,-100)
t.pendown()
t.write("By: Abbie Foster", font=("Arial", 15, "bold"), align="center")
t.end_fill()
# circle
t.penup()
t.goto(0,0)
t.pendown()
t.setheading(0)
t.pencolor("lightpink")
t.fillcolor("lightpink")
t.begin_fill()
t.circle(50)
t.end_fill()
# images
t.penup()
t.goto(-200,50)
t.pendown()
screen.addshape("flower.gif")
t.shape("flower.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(200,50)
t.pendown()
screen.addshape("beach.gif")
t.shape("beach.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-300)
t.pendown()
t.write("enter to continue", font=("Arial", 10, "bold"), align="center")
t.hideturtle()
round = input("Press enter to continue: ")
t.clear()
screen.bgcolor("lightpink")



# slide 2
t.penup()
t.goto(0,150)
t.pendown()
t.setheading(0)
t.pencolor("grey")
t.fillcolor("grey")
t.begin_fill()
t.write("My 3 Favorite Foods", font=("Arial", 30, "bold"), align="center")
t.end_fill()
# square
t.penup()
t.goto(-50, 230)
t.pendown()
t.setheading(0)
t.pencolor("hotpink")
t.fillcolor("hotpink")
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
# images
t.penup()
t.goto(-100,0)
t.pendown()
screen.addshape("food1.gif")
t.shape("food1.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(100,0)
t.pendown()
screen.addshape("food2.gif")
t.shape("food2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(-30,-150)
t.pendown()
screen.addshape("food3.gif")
t.shape("food3.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-300)
t.pendown()
t.setheading(0)
t.pencolor("grey")
t.fillcolor("grey")
t.begin_fill()
t.setheading(0)
t.pencolor("grey")
t.fillcolor("grey")
t.begin_fill()
t.write("enter to continue", font=("Arial", 10, "bold"), align="center")
t.end_fill()
t.end_fill()
t.hideturtle()
round = input("Press enter to continue: ")
t.clear()
screen.bgcolor("lightcoral")



# slide3
t.penup()
t.goto(0,150)
t.pendown()
t.setheading(0)
t.begin_fill()
t.pencolor("grey")
t.fillcolor("grey")
t.write("My Hobbies", font=("Arial", 30, "bold"), align="center")
t.end_fill()
# rectangle
t.penup()
t.goto(-50, 230)
t.pendown()
t.setheading(0)
t.pencolor("lightpink")
t.fillcolor("lightpink")
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(50)
t.left(90)
t.forward(100)
t.left(90)
t.forward(50)
t.end_fill()
# images
t.penup()
t.goto(-100,0)
t.pendown()
screen.addshape("hobbie1.gif")
t.shape("hobbie1.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(100,0)
t.pendown()
screen.addshape("hobbie2.gif")
t.shape("hobbie2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(-100,-150)
t.pendown()
screen.addshape("hobbie3.gif")
t.shape("hobbie3.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(100,-150)
t.pendown()
screen.addshape("hobbie4.gif")
t.shape("hobbie4.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-300)
t.pendown()
t.setheading(0)
t.pencolor("grey")
t.fillcolor("grey")
t.begin_fill()
t.write("enter to continue", font=("Arial", 10, "bold"), align="center")
t.end_fill()
t.hideturtle()
round = input("Press enter to continue: ")
t.clear()
screen.bgcolor("khaki1")



# slide4
t.penup()
t.goto(0,150)
t.pendown()
t.setheading(0)
t.pencolor("grey")
t.fillcolor("grey")
t.begin_fill()
t.write("My Favorite Movie", font=("Arial", 30, "bold"), align="center")
t.end_fill()
# rhombus
t.penup()
t.goto(50,300)
t.pendown()
t.setheading(135)
t.pencolor("lightyellow")
t.fillcolor("lightyellow")
t.begin_fill()
t.speed(1)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
# images
t.penup()
t.goto(0,-100)
t.pendown()
screen.addshape("movie1.gif")
t.shape("movie1.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,50)
t.pendown()
screen.addshape("movie2.gif")
t.shape("movie2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-300)
t.pendown()
t.setheading(0)
t.pencolor("grey")
t.fillcolor("grey")
t.begin_fill()
t.write("enter to continue", font=("Arial", 10, "bold"), align="center")
t.end_fill()
t.hideturtle()
round = input("Press enter to continue: ")
t.clear()
screen.bgcolor("lightblue")



# slide5
t.penup()
t.goto(0,150)
t.pendown()
t.setheading(0)
t.pencolor("grey")
t.fillcolor("grey")
t.begin_fill()
t.write("My Favorite Sport", font=("Arial", 30, "bold"), align="center")
t.end_fill()
# flower
t.penup()
t.goto(-200,0)
t.pendown()
t.pencolor("lightgreen")
t.pensize(8)
t.goto(-200,-100)
t.pensize(1)
t.penup()
t.goto(-200,0)
t.pendown()
t.pencolor("pink")
t.fillcolor("pink")
t.begin_fill()
t.circle(25)
t.setheading(90)
t.circle(25)
t.setheading(180)
t.circle(25)
t.setheading(270)
t.circle(25)
t.end_fill()
t.penup()
t.goto(-200,-15)
t.pendown()
t.setheading(0)
t.fillcolor("khaki")
t.begin_fill()
t.circle(15)
t.end_fill()
# images
t.penup()
t.goto(0,50)
t.pendown()
screen.addshape("sport1.gif")
t.shape("sport1.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-100)
t.pendown()
screen.addshape("sport2.gif")
t.shape("sport2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-300)
t.pendown()
t.setheading(0)
t.pencolor("grey")
t.fillcolor("grey")
t.begin_fill()
t.write("The End", font=("Arial", 10, "bold"), align="center")
t.end_fill()


t.hideturtle()
turtle.done()